#! /bin/csh -f
#############################################################################
#
# Script to compare working code version on RPi to configured version
#
#############################################################################
#
# Specify root where old version exists
#set ROOT="/media/${USER}/305f60b3-8413-4edb-afc1-4e4ce064aab3/home/${USER}"
#set ROOT="/media/${USER}/pi"
#set ROOT="/media/${USER}/aa2il"
set ROOT="/media/${USER}/marconi"
#set ROOT="/media/${USER}/3D76-ECB1/Xfer"
if( !(-e $ROOT) )then
    set ROOT="${ROOT}2"
endif

# Add path down to old version
set N=`echo $HOME | wc -c`
echo N=$N
#set PTH=`pwd | cut -c ${N}-`
set PTH=`pwd | sed 's;/home2;;g' | cut -c ${N}-`
echo PTH=$PTH
set old=${ROOT}${PTH}
echo OLD=$old
#exit

# Overide if necessary
#set OLD="work2"

rm -f DIFFS
foreach i (*.py AA2IL.adif sats.adif start* DIFF)
    echo $i
    set n=`diff -w $old/$i $i | wc -l`
    if( $n>0 ) then
        echo ---------------------------------- >> DIFFS
        echo $i >> DIFFS
        echo " " >> DIFFS
        diff -w $old/$i $i >> DIFFS
        echo " " >> DIFFS
        
        kompare $old/$i $i
        #kompare $i $old/$i
    endif
end

chmod +x pyKeyer.py DIFF

cat DIFFS
