#! /usr/bin/tcsh
###############################################################################

# Start - J.B.Attili - 2023

# Script showing how to start the keyer for practice.

###############################################################################

set NANO=""
set NANO="-nano"

# Pick one
set CONTEST="cwt"
#set CONTEST="sst"
#set CONTEST="mst"
#set CONTEST="naqp"

###############################################################################

# Start keyer
set OPTS="-prac -wpm 30 -adjust -sending $NANO -$CONTEST"
#echo OPTS=$OPTS

cd ~/Python/pyKeyer/dist
set CMD="pyKeyer $OPTS"
echo CMD=$CMD
$CMD


