#! /usr/bin/tcsh
############################################################################################

# Start - J.B.Attili - 2018-2025

# Script showing how to start the keyer for various contests and practice.

############################################################################################

cls

# Primary rig
set RIG="NONE"
#set RIG="HAMLIB"
#set RIG="DIRECT"
#set RIG1="FLRIG"
#set RIG="ANY"

set RIG_TYPE=""
#set RIG_TYPE="FTdx3000"
#set RIG_TYPE="FT991a"
#set RIG_TYPE="IC9700"

# Secondary rig for SO2R
set RIG2="NONE"
#set RIG2="DIRECT"
#set RIG_TYPE2="FT991a"
#set RIG_TYPE2="IC9700"

# Rig finder
set PYTHON=""
#conda activate aa2il
#conda activate py3_13
#set PYTHON="python"
#which python
set FIND_RIG="$PYTHON ~/Python/findRig/findRig.py"

# Various prog options
set PRACTICE=""
set PRACTICE="-prac -nrows 0"
#set PRACTICE="-prac -nrows 0 -lock"

set NANO=""
#set NANO="-keyer ANY"
#set NANO="-keyer NONE"
#set NANO="-nano"
#set NANO="-k3ng"
set NANO="-winkeyer "

#set NANO="-sidetone"
#set NANO="-nano -sidetone"

set KILL_OLD = 0

set WPM=25
set HINTS=""
#set HINTS="-hints"

set CA_ONLY=""
set CA_ONLY="-ca_only"

set SCP=""
set SCP="-scp"

set AGGRESSIVE=""
set AGGRESSIVE="-aggressive"

# Pick a contest
set CONTEST="paddling"
#set CONTEST="cwt"
#set CONTEST="sst"
#set CONTEST="mst"
#set CONTEST="sprint"
#set CONTEST="foc"

#set CONTEST="wpx"
#set CONTEST="naqp"
#set CONTEST="cq160m"
#set CONTEST="arrl_dx"
#set CONTEST="vhf"
#set CONTEST="fd"
set CONTEST="iaru"
#set CONTEST="cqvhf"
#set CONTEST="stew"
#set CONTEST="sat"
#set CONTEST="cqp"
#set CONTEST="ss"
#set CONTEST="cqww"
set CONTEST="cwopen"
#set CONTEST="ten"
#set CONTEST="arrl_160m"
#set CONTEST="arrl_10m"
#set CONTEST="rac"

#set CONTEST="state"

#set CONTEST="default"
#set CONTEST="ragchew"
#set CONTEST="dx"
#set CONTEST="skcc"
#set CONTEST="calls"

#set CAPTURE="-capture -sidetone"
#set CAPTURE="-capture"
#set CAPTURE=""

#set STATE="CP"

########################################################################

# Determine current workspace number - we'll use this later to
# keep windows on this workspace instead of wandering
echo " "
set WS=`wmctrl -d | fgrep " * " | cut -f 1 -d ' '`
echo Current Workspace = $WS
echo " "

# Force unbuffered output to stdout - same as python -u opt
setenv PYTHONUNBUFFERED 1

# Settings for sending practice
if( ($CONTEST == "paddling") && ($RIG != "NONE") )then
    echo rig=$RIG
    echo $FIND_RIG
    pkill flrig
    set RIG9=`$FIND_RIG`
    echo $RIG9
    echo rig9=$RIG9 rig=$RIG
    if( $RIG9 == "None" )then
        #set RIG="NONE"
        echo "---- ERROR - Cant find rig ----"
        echo Make sure serial ports arent hosed up - reset if needed
        exit
    endif
    #exit
else if( ($CONTEST == "paddling") && ($RIG == "NONE9") )then
    #pkill flrig
    set RIG9=`$FIND_RIG`
    if( $RIG9 != "None" )then
        set RIG="DIRECT"
        set RIG_TYPE=$RIG9
    endif
    echo $RIG9 $RIG
    #exit
endif

if( $CONTEST == "paddling" )then
    if( $RIG != "NONE" )then
        set CMD="$FIND_RIG -BREAK 0"
        echo $CMD
        $CMD
    endif
    set WPM=20
    set CONTEST="ragchew"
    set HINTS="-adjust -sending  -immediate"
    #exit
    
########################################################################
    
# Settings for NAQP contest
else if( $CONTEST == "naqp" )then
    set WPM=30
    set HINTS="-adjust"
    #set HINTS="-adjust -autofill -scp"

# Settings for CW Ops mini tests
else if( $CONTEST == "cwt" )then
    set WPM=30
    set HINTS="-adjust"
    #set HINTS=""

# Settings for FOC BW
else if( $CONTEST == "foc" )then
    set WPM=30
    set HINTS="-adjust"

# Settings for NCCC Sprints
else if( $CONTEST == "sprint" )then
    set WPM=25
    #set HINTS="-adjust"
    set HINTS=""
    set SCP=""

# Settings for K1USN slow speed tests
else if( $CONTEST == "sst" )then
    set WPM=20
    set HINTS="-lock"
    #set HINTS="-adjust -lock"
    #set HINTS="-adjust -autofill"
    #set HINTS="-use_log_hist -autofill -nrows 1"

# Settings for ICWC Medium speed tests
else if( $CONTEST == "mst" )then
    set WPM=25
    set HINTS="-lock"
    #set HINTS="-adjust"

# Settings for NCCC CW Sprints
else if( $CONTEST == "sprint" )then
    set WPM=25
    set CONTEST="-sprint"
    set HINTS=""

# Settings for CW Ops cw open
else if( $CONTEST == "cwopen" )then
    set WPM=30
    set HINTS="-adjust"

# Setting for CQ WPX (or any contest that requires rst + serial number)
else if( $CONTEST == "wpx" )then
    set WPM=30
    set HINTS="-adjust"

# Setting for CQ World Wide
else if( $CONTEST == "cqww" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for field day
else if( $CONTEST == "fd" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for IARU HF Champs
else if( $CONTEST == "iaru" )then
    set WPM=30
    set HINTS=" -adjust"

# Settings for CA QSO Party
else if( $CONTEST == "cqp" )then
    set WPM=30
    set HINTS="-adjust $CA_ONLY"

# Settings for ARRL & CQ VHF
else if( $CONTEST == "vhf" || $CONTEST == "cqvhf" )then
    set WPM=25

# Settings for Stew Perry - need to test this out
else if( $CONTEST == "vhf" )then
    set WPM=25

# Settings for satellites
else if( $CONTEST == "sat" )then
    set WPM=25

# Settings for ARRL 160m
else if( $CONTEST == "arrl_160m" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for ARRL 10m
else if( $CONTEST == "arrl_10m" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for CQ 160m
else if( $CONTEST == "cq160m" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for 10-10 10m
else if( $CONTEST == "ten" )then
    set WPM=25
    set HINTS=""

# Settings for ARRL Intl DX - need to test this more, not sure it handles dx stations correctly
else if( $CONTEST == "arrl_dx" )then
    set WPM=30
    set HINTS=""

# Settings for ARRL Sweepstakes
else if( $CONTEST == "ss" )then
    set WPM=30
    set HINTS=""
    set HINTS="-adjust"

# Settings for SKCC practice
else if( $CONTEST == "skcc" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for random calls practice
else if( $CONTEST == "calls" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for Default Quick, Ragchew or QSOs
else if( $CONTEST == "default" || $CONTEST == "ragchew"  || $CONTEST == "dx" )then
    set WPM=22
    set HINTS="-use_log_hist -autofill -nrows 0 -lock -sending"

# Settings for various state QPs
else if( $CONTEST == "state" )then
    set CONTEST="state $STATE"
    set WPM=25
    set HINTS=""

# RAC contest
else if( $CONTEST == "rac" )then
    set WPM=25
    set HINTS=""
    
else
    echo START: Unknown Contest -$CONTEST-
    exit
endif

########################################################################

# Clean-up
if( $KILL_OLD )then
    pkill pyKeyer
    pkill pyLogger
    pkill flrig
    pkill rigctl
    pkill rigctld
endif

########################################################################

# Setup for Hamlib
if( $RIG != "HAMLIB" )then
    echo No Hamlib
else if( $RIG_TYPE == "FTdx3000" )then
    set DEVICE="/dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_AH046H3M120067-if00-port0"
    set MODEL = 129
else if( $RIG_TYPE == "FT991a" )then
    set DEVICE = "/dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_00A50791-if00-port0"
    set MODEL = 135 
else
    echo " "
    echo Error configuring HAMLIB - Unknown rig type $RIG_TYPE
    echo " "
    exit
endif 

# Start hamlib
if( $RIG == "HAMLIB" )then
    set a=`ls -l $DEVICE`
    echo -$a-
    set b=`echo $a | cut -f 2 -d '>'`
    echo -$b-
    set c=`echo $b | cut -f 3 -d '/'`
    echo -$c-
    
    set EXE_DIR="~/hamlib-3.3/tests"
    $EXE_DIR/rigctld -m $MODEL -r /dev/$c >&/tmp/HAMLIB &
    sleep 1
    
    echo "Rigctl daemon started."
    ps -A u | fgrep -i rigctl

    #exit
endif 

################################################################################

if( "X$PRACTICE" == "" )then
    set CAPTURE="-capture"
else
    set CAPTURE=""
endif

# Start keyer
pkill pyKeyer
set OPTS="-wpm ${WPM} $PRACTICE $NANO -${CONTEST} -rig $RIG $RIG_TYPE $HINTS $CAPTURE $SCP $AGGRESSIVE -desktop $WS"
if( $RIG2 != "NONE" )then
    set OPTS="$OPTS -rig2 $RIG2 $RIG_TYPE2"
endif
echo " "
echo OPTS=$OPTS
echo " "

cd ~/Python/pyKeyer
set EXE="$PYTHON pyKeyer.py"
#cd dist
#set EXE="pyKeyer"
pwd

set TMP="/tmp/KEYER"
echo $EXE $OPTS 
echo " "        >&  $TMP
echo $EXE $OPTS >>& $TMP
echo " "        >>& $TMP
#$EXE $OPTS      >>& $TMP &
#tail -f $TMP
$EXE $OPTS
