#! /usr/bin/tcsh
############################################################################################

# Start - J.B.Attili - 2018

# Script showing how to start the keyer for various contests and practice.

############################################################################################

# Primary rig
set RIG="NONE"
#set RIG="HAMLIB"
#set RIG="DIRECT"
#set RIG="ANY"

set RIG_TYPE=""
#set RIG_TYPE="FTdx3000"
#set RIG_TYPE="FT991a"
#set RIG_TYPE="IC9700"

# Secondary rig for SO2R
set RIG2="NONE"
#set RIG2="DIRECT"
#set RIG_TYPE2="FT991a"
#set RIG_TYPE2="IC9700"

set KILL_OLD = 0
set FIND_RIG="~/Python/findRig/findRig.py"

############################################################################################

set PRACTICE=""
set PRACTICE="-prac -nrows 0"
set PRACTICE="-prac -nrows 0 -lock"
set NANO=""
set NANO="-nano"

set WPM=25
set HINTS="-nohints"

set CA_ONLY=""
#set CA_ONLY="-ca_only"

set CONTEST="paddling"
#set CONTEST="ten"
#set CONTEST="cwt"
#set CONTEST="sst"
#set CONTEST="mst"
#set CONTEST="cwopen"
#set CONTEST="skcc"
#set CONTEST="calls"

#set CONTEST="iaru"
#set CONTEST="naqp"
#set CONTEST="fd"
#set CONTEST="vhf"
#set CONTEST="cqvhf"
#set CONTEST="stew"
#set CONTEST="sat"
#set CONTEST="cqp"
#set CONTEST="state"
#set CONTEST="wpx"
#set CONTEST="ss"
#set CONTEST="cqww"
#set CONTEST="arrl_10m"
#set CONTEST="arrl_dx"
#set CONTEST="default"
#set CONTEST="ragchew"
#set CONTEST="dx"

#set CAPTURE="-capture -sidetone"
#set CAPTURE="-capture"
#set CAPTURE=""

set STATE="NV"

########################################################################

# Settings for sending practice
if( $CONTEST == "paddling" )then
    set CMD="$FIND_RIG -BREAK 0"
    $CMD
    set WPM=20
    set CONTEST="ragchew"
    set HINTS="-nohints -adjust -sending  -immediate"

# Settings for NAQP contest
else if( $CONTEST == "naqp" )then
    set WPM=30
    set HINTS="-nohints -adjust"
    #set HINTS="-nohints -adjust -autofill -scp"

# Settings for CW Ops mini tests
else if( $CONTEST == "cwt" )then
    set WPM=30
    set HINTS="-nohints -adjust"
    #set HINTS=""

# Settings for K1USN slow speed tests
else if( $CONTEST == "sst" )then
    set WPM=20
    set HINTS="-nohints -adjust"
    #set HINTS="-nohints -adjust -autofill"
    #set HINTS="-use_log_hist -nohints -autofill -nrows 1"

# Settings for ICWC Medium speed tests
else if( $CONTEST == "mst" )then
    set WPM=25
    set HINTS="-nohints -adjust"

# Settings for NCCC CW Sprints
else if( $CONTEST == "sprint" )then
    set WPM=25
    set CONTEST="-sprint"
    set HINTS=""

# Settings for CW Ops cw open
else if( $CONTEST == "cwopen" )then
    set WPM=30
    set HINTS="-adjust"

# Setting for CQ WPX (or any contest that requires rst + serial number)
else if( $CONTEST == "wpx" )then
    set WPM=30
    set HINTS="-adjust"

# Setting for CQ World Wide
else if( $CONTEST == "cqww" )then
    set WPM=25
    set HINTS=""

# Settings for field day
else if( $CONTEST == "fd" )then
    set WPM=25
    #set HINTS="-nohints"
    set HINTS="-nohints -adjust"

# Settings for IARU HF Champs
else if( $CONTEST == "iaru" )then
    set WPM=30
    set HINTS=" -adjust"

# Settings for CA QSO Party
else if( $CONTEST == "cqp" )then
    set WPM=30
    set HINTS="-nohints -adjust $CA_ONLY"

# Settings for ARRL & CQ VHF
else if( $CONTEST == "vhf" || $CONTEST == "cqvhf" )then
    set WPM=25

# Settings for Stew Perry - need to test this out
else if( $CONTEST == "vhf" )then
    set WPM=25

# Settings for satellites
else if( $CONTEST == "sat" )then
    set WPM=25

# Settings for ARRL 10m
else if( $CONTEST == "arrl_10m" )then
    set WPM=25
    set HINTS=""

# Settings for 10-10 10m
else if( $CONTEST == "ten" )then
    set WPM=25
    set HINTS=""

# Settings for ARRL Intl DX - need to test this more, not sure it handles dx stations correctly
else if( $CONTEST == "arrl_dx" )then
    set WPM=30
    set HINTS=""

# Settings for ARRL Sweepstakes
else if( $CONTEST == "ss" )then
    set WPM=30
    set HINTS=""
    set HINTS="-adjust"
    #set HINTS="-nohints -adjust"

# Settings for SKCC practice
else if( $CONTEST == "skcc" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for random calls practice
else if( $CONTEST == "calls" )then
    set WPM=25
    set HINTS="-adjust"

# Settings for Default Quick, Ragchew or QSOs
else if( $CONTEST == "default" || $CONTEST == "ragchew"  || $CONTEST == "dx" )then
    set WPM=22
    set HINTS=""
    set HINTS="-use_log_hist -nohints -autofill -nrows 0 -lock -sending"

# Settings for various state QPs
else if( $CONTEST == "state" )then
    set CONTEST="state $STATE"
    set WPM=25
    set HINTS=""

else
    echo START: Unknown Contest -$CONTEST-
    exit
endif

########################################################################

# Clean-up
if( $KILL_OLD )then
    pkill pyKeyer
    pkill flrig
    pkill rigctl
    pkill rigctld
endif

########################################################################

# Setup for Hamlib
if( $RIG != "HAMLIB" )then
    echo No Hamlib
else if( $RIG_TYPE == "FTdx3000" )then
    set DEVICE="/dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_AH046H3M120067-if00-port0"
    set MODEL = 129
else if( $RIG_TYPE == "FT991a" )then
    set DEVICE = "/dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_00A50791-if00-port0"
    set MODEL = 135 
else
    echo " "
    echo Error configuring HAMLIB - Unknown rig type $RIG_TYPE
    echo " "
    exit
endif 

# Start hamlib
if( $RIG == "HAMLIB" )then
    set a=`ls -l $DEVICE`
    echo -$a-
    set b=`echo $a | cut -f 2 -d '>'`
    echo -$b-
    set c=`echo $b | cut -f 3 -d '/'`
    echo -$c-
    
    set EXE_DIR="~/hamlib-3.3/tests"
    $EXE_DIR/rigctld -m $MODEL -r /dev/$c >&/tmp/HAMLIB &
    sleep 1
    
    echo "Rigctl daemon started."
    ps -A u | fgrep -i rigctl

    #exit
endif 

################################################################################

if( "X$PRACTICE" == "" )then
    set CAPTURE="-capture"
else
    set CAPTURE=""
endif

# Start keyer
set OPTS="-wpm ${WPM} $PRACTICE $NANO -${CONTEST} -rig $RIG $RIG_TYPE $HINTS $CAPTURE"
if( $RIG2 != "NONE" )then
    set OPTS="$OPTS -rig2 $RIG2 $RIG_TYPE2"
endif
echo OPTS=$OPTS

cd ~/Python/pyKeyer
#echo pyKeyer.py $OPTS >& /tmp/KEYER
echo pyKeyer.py $OPTS 
#pyKeyer.py $OPTS >>& /tmp/KEYER &
pyKeyer.py $OPTS
